language: go

go:
  - 1.x

install:
  - go get github.com/stretchr/testify
  - go get github.com/shoenig/toolkit
  - go get github.com/pkg/errors

script:
  - go build ./...
  - go vet ./...
  - go test ./...
